Fixed AttributeError: 'module' object has no attribute 'make_avsc_object'
make_avsc_object is deprecated in Python 3.x avro module and replaced by SchemaFromJSONData.

Read:
http://programtalk.com/python-examples/avro.schema.make_avsc_object/
http://programtalk.com/vs2/python/10728/rabix/rabix/common/models.py/