Fixed AttributeError: 'str' object has no attribute 'decode'
There is no need to decode from UTF-8 anymore.

Read:
https://stackoverflow.com/questions/28583565/str-object-has-no-attribute-decode-python-3-error